version: '3.7'

services:
  nginx:
    image: nginx:latest #can not load images nginx:latest
    ports:
      - 443:443 #443:443
    # volumes:
    #   - ./html:usr/share/nginx/html

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    # environment:
    #   - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
    env_file:
      - .env
    # volumes:
    #   - ./html:usr/share/mariadb/html

  wordpress:
    image: wordpress:latest
    ports:
      - 9000:9000
    # volumes:
    #   - ./html:usr/share/wordpress/html

