version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html/wordpress
      # - ./requirements/nginx/conf/:/etc/nginx/http.d/
      # - ./requirements/nginx/tools:/etc/nginx/ssl/
    restart: always

    ####### STATIC WEBSITE#######
  html:
    container_name: html
    build:
      context: ./requirements/bonus
      dockerfile: ./html/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - inception

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
# arg for image creation RUN and env_file for container CMD runtime